env_conf_d = true

{% set flatpak = "/usr/share/wayland-sessions" is dir or "/usr/share/xsessions" is dir %}
{% set arch = "/etc/arch-release" is file %}
{% set fedora = "/etc/fedora-release" is file %}
{% set rhel = "/etc/redhat-release" is file %}
{% set ubuntu = "/etc/lsb-release" is file and "/usr/share/keyrings/ubuntu-archive-keyring.gpg" is file %}
{% set debian = "/etc/debian_version" is file %}

{% if arch %}
{% if flatpak %}
env = ["arch", "pacman", "flatpak"]
{% else %}
env = ["arch", "pacman"]
{% endif %}
{% elif fedora %}
{% if flatpak %}
env = ["fedora", "dnf", "flatpak"]
{% else %}
env = ["fedora", "dnf"]
{% endif %}
{% elif rhel %}
{% if flatpak %}
env = ["rhel", "dnf", "flatpak"]
{% else %}
env = ["rhel", "dnf"]
{% endif %}
{% elif ubuntu %}
{% if flatpak %}
env = ["ubuntu", "apt", "flatpak"]
{% else %}
env = ["ubuntu", "apt"]
{% endif %}
{% elif debian %}
{% if flatpak %}
env = ["debian", "apt", "flatpak"]
{% else %}
env = ["debian", "apt"]
{% endif %}
{% elif flatpak %}
env = ["flatpak"]
{% endif %}
