[bootstrap.hooks.pre-packages]
run = 'sh "$HOME/.dotfiles/scripts/bootstrap-pre-packages.sh"'

[bootstrap.packages]
"apt:fcitx5" = "latest"
"apt:fcitx5-chewing" = "latest"
"apt:fcitx5-frontend-all" = "latest"
"apt:ghostty" = "latest"
"apt:software-properties-common" = "latest"
"apt:wl-clipboard" = "latest"
"apt:xdg-terminal-exec" = "latest"
"flatpak-user:com.bitwarden.desktop" = "latest"
"flatpak-user:com.borgbase.Vorta" = "latest"
"flatpak-user:com.dec05eba.gpu_screen_recorder" = "latest"
"flatpak-user:com.github.Matoking.protontricks" = "latest"
"flatpak-user:com.github.marhkb.Pods" = "latest"
"flatpak-user:com.github.tchx84.Flatseal" = "latest"
"flatpak-user:com.heroicgameslauncher.hgl" = "latest"
"flatpak-user:com.obsproject.Studio" = "latest"
"flatpak-user:com.ranfdev.DistroShelf" = "latest"
"flatpak-user:com.rustdesk.RustDesk" = "latest"
"flatpak-user:com.usebottles.bottles" = "latest"
"flatpak-user:com.vysp3r.ProtonPlus" = "latest"
"flatpak-user:dev.vencord.Vesktop" = "latest"
"flatpak-user:dev.zed.Zed" = "latest"
"flatpak-user:io.ente.auth" = "latest"
"flatpak-user:io.github.avomar.dev-toolbox" = "latest"
"flatpak-user:io.github.flattool.Warehouse" = "latest"
"flatpak-user:io.github.ilya_zlobintsev.LACT" = "latest"
"flatpak-user:io.github.wiiznokes.fan-control" = "latest"
"flatpak-user:io.github.zarestia_dev.rclone-manager" = "latest"
"flatpak-user:io.missioncenter.MissionCenter" = "latest"
"flatpak-user:io.podman_desktop.PodmanDesktop" = "latest"
"flatpak-user:it.mijorus.gearlever" = "latest"
"flatpak-user:md.obsidian.Obsidian" = "latest"
"flatpak-user:net.nokyan.Resources" = "latest"
"flatpak-user:net.retrodeck.retrodeck" = "latest"
"flatpak-user:org.audacityteam.Audacity" = "latest"
"flatpak-user:org.gnome.Calculator" = "latest"
"flatpak-user:org.localsend.localsend_app" = "latest"
"flatpak-user:org.nickvision.tubeconverter" = "latest"
"flatpak-user:org.onlyoffice.desktopeditors" = "latest"
"flatpak-user:org.signal.Signal" = "latest"
"flatpak-user:org.telegram.desktop" = "latest"

[dotfiles]
"~/.config/ghostty/config" = {}
"~/.config/fcitx5/profile" = {}
"~/.config/environment.d/90-fcitx5.conf" = {}
"~/.config/xdg-terminals.list" = {}
"~/.local/share/xdg-terminals/com.mitchellh.ghostty.desktop" = "/usr/share/applications/com.mitchellh.ghostty.desktop"
