[bootstrap.hooks.pre-packages]
run = 'sh "$HOME/.dotfiles/scripts/bootstrap-pre-packages.sh" pacman'

[bootstrap.packages]
"pacman:openssh" = "latest"
"pacman:zsh" = "latest"
"pacman:flatpak" = "latest"
