[bootstrap.packages]
"apt:openssh-client" = "latest"
"apt:zsh" = "latest"
"apt:unattended-upgrades" = "latest"
"apt:fcitx5" = "latest"
"apt:fcitx5-chewing" = "latest"
"apt:fcitx5-frontend-all" = "latest"
"apt:libnotify-bin" = "latest"
"apt:wl-clipboard" = "latest"
"apt:xdg-terminal-exec" = "latest"

[bootstrap.files."/etc/apt/apt.conf.d/20auto-upgrades"]
content = '''
APT::Periodic::Enable "1";
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
'''
owner = "root"
group = "root"
mode = "0644"

[bootstrap.services."apt-daily.timer"]
enabled = true
state = "running"

[bootstrap.services."apt-daily-upgrade.timer"]
enabled = true
state = "running"

[dotfiles]
"~/.config/fcitx5/profile" = {}
"~/.config/environment.d/90-fcitx5.conf" = {}
