[bootstrap.packages]
"dnf:gcc" = "latest"
"dnf:gcc-c++" = "latest"
"dnf:fontconfig" = "latest"
"dnf:xz" = "latest"
"dnf:cmake" = "latest"
"dnf:extra-cmake-modules" = "latest"
"dnf:gettext" = "latest"
"dnf:fcitx5-devel" = "latest"
"dnf:fmt-devel" = "latest"
"dnf:libicu-devel" = "latest"
"dnf:json-c-devel" = "latest"
"dnf:curl" = "latest"
"dnf:nmap" = "latest"
"dnf:openssh-clients" = "latest"
"dnf:zsh" = "latest"
"dnf:dnf-automatic" = "latest"
"dnf:fcitx5" = "latest"
"dnf:fcitx5-gtk2" = "latest"
"dnf:fcitx5-gtk3" = "latest"
"dnf:fcitx5-gtk4" = "latest"
"dnf:fcitx5-qt5" = "latest"
"dnf:fcitx5-qt6" = "latest"
"dnf:libnotify" = "latest"
"dnf:wl-clipboard" = "latest"
"dnf:xdg-terminal-exec" = "latest"

[bootstrap.hooks.post-packages]
run = 'sh "${MISE_CONFIG_DIR:-$HOME/.config/mise}/scripts/install-mcbopomofo.sh"'
