[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:fontconfig" = "latest"
"apt:xz-utils" = "latest"
"apt:pkg-config" = "latest"
"apt:libdbus-1-dev" = "latest"
"apt:nmap" = "latest"
"apt:openssh-client" = "latest"
"apt:zsh" = "latest"
"apt:unattended-upgrades" = "latest"
"apt:fcitx5" = "latest"
"apt:fcitx5-chewing" = "latest"
"apt:fcitx5-frontend-all" = "latest"
"apt:libnotify-bin" = "latest"
"apt:wl-clipboard" = "latest"
"apt:xdg-terminal-exec" = "latest"
"apt:nala" = "latest"

[bootstrap.files."/etc/apt/apt.conf.d/20auto-upgrades"]
content = '''
APT::Periodic::Enable "1";
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
'''
owner = "root"
group = "root"
mode = "0644"

[bootstrap.services."apt-daily.timer"]
enabled = true
state = "running"

[bootstrap.services."apt-daily-upgrade.timer"]
enabled = true
state = "running"

[dotfiles]
"~/.config/fcitx5/profile" = { source = "../.config/fcitx5/profile" }
"~/.config/environment.d/90-fcitx5.conf" = { source = "../.config/environment.d/90-fcitx5.conf" }

[shell_alias]
apt = "nala"
