[settings]
disable_tools = [
  "github:ryanoasis/nerd-fonts",
  "github:tinted-theming/tinty",
]

[shell_alias]
update = "omarchy update"

[dotfiles]
"~/.config/omarchy/themed/gomi.yaml.tpl" = { mode = "track" }
"~/.config/omarchy/themed-links.toml" = { mode = "track" }
"~/.config/omarchy/hooks/theme-set.d/50-themed-links" = { mode = "track" }

[bootstrap.user]
login_shell = "/usr/bin/bash"

[bootstrap.hooks.post-tools]
run = '''
bash "$HOME/.config/omarchy/hooks/theme-set.d/50-themed-links" --ensure-rendered
'''

[tasks."bootstrap:theme"]
hide = true
run = ":"
