[dotfiles]
"~/.config/omarchy/themed/gomi.yaml.tpl" = { mode = "track" }

[bootstrap.hooks.post-dotfiles]
run = '''
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/gomi"
mkdir -p "$config_dir"
rm -f "$config_dir/config.yaml"
ln -s "$HOME/.local/state/omarchy/current/theme/gomi.yaml" "$config_dir/config.yaml"
'''
