[bootstrap.packages]
"pacman:base-devel" = "latest"
"pacman:pkgconf" = "latest"
"pacman:dbus" = "latest"
"pacman:fontconfig" = "latest"
"pacman:xz" = "latest"
"pacman:nmap" = "latest"
"pacman:openssh" = "latest"
"pacman:zsh" = "latest"
"pacman:fcitx5" = "latest"
"pacman:fcitx5-chewing" = "latest"
"pacman:fcitx5-gtk" = "latest"
"pacman:fcitx5-qt" = "latest"
"pacman:libnotify" = "latest"
"pacman:wl-clipboard" = "latest"
