schema_version = 1

[tools]
codex = { zsh = "codex completion zsh" }
dasel = "standard"
gup = "standard"
herdr = "standard"
sheldon = { zsh = "sheldon completions --shell zsh" }
topgrade = { zsh = "topgrade --gen-completion zsh" }
witr = "standard"
