schema_version = 1

[tools]
dasel = "standard"
gup = "standard"
herdr = "standard"
sheldon = { zsh = "sheldon completions --shell zsh" }
topgrade = { zsh = "topgrade --gen-completion zsh" }
witr = "standard"
